# Exercises

## Search algorithms

Let's look at two different kinds of search algorithms: linear and binary.

In [1]:
def linear_search(items, desired_item):
    for position, item in enumerate(items):
        if item == desired_item:
            return position

    raise ValueError("%s was not found in the list." % desired_item)

In [82]:
def binary_search(arr, x):
    sorted_ind = np.argsort(arr)
    
    sorted_arr = arr[sorted_ind]
    
    low = 0
    high = len(arr) - 1
    mid = 0
 
    while low <= high:
 
        mid = (high + low) // 2
 
        # If x is greater, ignore left half
        if sorted_arr[mid] < x:
            low = mid + 1
 
        # If x is smaller, ignore right half
        elif sorted_arr[mid] > x:
            high = mid - 1
 
        # means x is present at mid
        else:
            return sorted_arr[sorted_ind]
 
    # If we reach here, then the element was not present
    return -1


Create a Python list with several thousand of random elements. Append the element `10` and shuffle the list.

In [83]:
import numpy as np

In [84]:
np.random.seed(8675309)
my_list = np.random.rand(3000)

In [85]:
my_list = np.append(my_list, 10)

In [86]:
np.random.shuffle(my_list)

In [87]:
my_list

array([0.9323314 , 0.31700092, 0.96440175, ..., 0.29582148, 0.3702895 ,
       0.56001133])

Create an optmized array either with Numpy, Pandas, or other library you want to test that contains the same amount of random elements of the previous array

In [88]:
opt_array = np.random.rand(3001)
opt_array[3000] = 10
print(opt_array)
np.random.shuffle(opt_array)

[ 0.05635521  0.1203399   0.96778893 ...  0.03758552  0.10786633
 10.        ]


In [89]:
print(opt_array)

[0.5997307  0.05685228 0.08638047 ... 0.1879122  0.85144655 0.81182335]


In [90]:
import time

Perform a simple bench mark using both arrays and both search methods. What is faster? Does it corresponds with your intuition?

In [91]:
t0 = time.time()
q = linear_search(my_list, 10)
t1 = time.time()
search1 = t1-t0

t2 = time.time()
linear_search(opt_array, 10)
t3 = time.time()
search2 = t3-t2

In [92]:
q

1150

In [93]:
print(search1)
print(search2)

0.00039124488830566406
0.00044083595275878906


In [94]:
t0 = time.time()
binary_search(my_list, 10)
t1 = time.time()
search1 = t1-t0

t2 = time.time()
q = binary_search(opt_array, 10)
t3 = time.time()
search2 = t3-t2

In [95]:
q

array([0.07554613, 0.18776733, 0.5705349 , ..., 0.82253198, 0.97812092,
       0.44190421])

In [96]:
print(search1)
print(search2)

0.001062154769897461
0.0005853176116943359


Print the index where the element was found in each one of the structures.

Add a new element to the data structures you just created. Append the element `20`, but this time don't suffle the structures. If you perform the same benchmarks what do you observe?

Can you infer what's the Big O complexity of the algorithms?

What are the circunstances in which you should use one or the other kind of search? What are the cases and the specific kinds of arrays in which each search makes the most sense to be used?

## List comprehensions

Let's test the power of list comprehensions.

In [80]:
import pandas as pd
import numpy as np


df = pd.DataFrame({
        "a": np.random.randn(1000),
        "b": np.random.randn(1000),
        "N": np.random.randint(100, 1000, (1000)),
        "x": "x",
    })
df

a         b    N  x
0    1.773967 -0.017413  499  x
1   -1.455513  1.804807  853  x
2    0.278826  0.150128  857  x
3   -1.148026 -1.135163  877  x
4    1.082627 -0.227627  761  x
..        ...       ...  ... ..
995 -0.083906  1.266433  806  x
996  0.744000 -0.209710  716  x
997  0.197511 -0.134100  225  x
998 -0.604882  0.083294  856  x
999  0.487488  1.426160  851  x

[1000 rows x 4 columns]

In [81]:
def f(x):
    return x * (x - 1)

def integrate_f(a, b, N):
    s = 0
    dx = (b - a) / N

    for i in range(N):
        s += f(a + i * dx)

    return s * dx

Usind the data set and the `integrate_f` function above write a function that uses the `integrate_f` as a `for` loop and another one in the form of a `lambda`. Use `df.apply` to apply the results of your `lambda`.

Now use the `timeit`, `prun -l N`(N is the number of lines you want to have displayed) and `snakevyz` to check the different processing times

## Optimizing Python functions

Try to optmize the following function:

In [23]:
def vowel_count(str):
    # Initializing count variable to 0
    count = 0
      
    # Creating a set of vowels
    vowel = set("aeiouAEIOU")
      
    # Loop to traverse the alphabet
    # in the given string
    for alphabet in str:
      
        # If alphabet is present
        # in set vowel
        if alphabet in vowel:
            count = count + 1

Use this function as an input for your `vowel_count` function.

In [24]:
import random
import string


def random_char(y):
       return ''.join(random.choice(string.ascii_letters) for x in range(y))

Here's another function you can try:

Before starting to code anything and thinking about the tools that were presented in this class, do you have an idea for which tool you could use to optimize the following function?

In [ ]:
def steps_to(stair):
    if stair == 1:
        return 1
    elif stair == 2:
        return 2
    elif stair == 3:
        return 4
    else:
        return (steps_to(stair - 3)
                + steps_to(stair - 2)
                + steps_to(stair - 1))

## Numba performance

Numba has to compile your function for the argument types given before it executes the machine code version of your function, this takes time. However, once the compilation has taken place Numba caches the machine code version of your function for the particular types of arguments presented. If it is called again the with same types, it can reuse the cached version instead of having to compile again.

A really common mistake when measuring performance is to not account for the above behaviour and to time code once with a simple timer that includes the time taken to compile your function in the execution time.

Using the `timeit` module is a way of avoiding this.

In [ ]:
!pip install numba

In [ ]:
from numba import jit, njit

Use the following options to test the code in the next cell:

    parallel = True - enable the automatic parallelization of the function.
    parallel = True - enable the automatic parallelization of the function.

    fastmath = True - enable fast-math behaviour for the function. (If true, fastmath enables the use of otherwise unsafe floating point transforms as described in the LLVM documentation.)

These are arguments for the `jit` decorator we saw earlier in the examples.

`njit` and `jit(nopython=True` are the same. This means that Numba tries to release the global interpreter lock inside the compiled function. The GIL will only be released if Numba can compile the function in nopython mode, otherwise a compilation warning will be printed. 

In [ ]:
def do_sum(A):
    acc = 0.
    # without fastmath, this loop must accumulate in strict order
    for x in A:
        acc += np.sqrt(x)
    return acc

def do_sum_fast(A):
    acc = 0.
    # with fastmath, the reduction can be vectorized as floating point
    # reassociation is permitted.
    for x in A:
        acc += np.sqrt(x)
    return acc

# Interacting with I/O

Let's compare some I/O flows. 

In the following cells the code to create a dataset using `h5py` was given to you.

In [ ]:
!pip install h5py

In [ ]:
import h5py

array = np.random.random(size=(10))
h5f = h5py.File('data.h5', 'w')
h5f.create_dataset('dataset', data = array)

In [ ]:
h5_loaded = h5f['dataset'][:]

In [ ]:
for i in range(len(h5_loaded)):
    h5_loaded[i] = 1

Implement an equivalent dataset to this one, but this time using Python's CSV. If you want also give it a try using Pandas and Numpy.

Change the parameters in this function, things like the size of `np` array and the operation executed inside the `for` loop, maybe you want to add a transformation to each value of the dataset. Explore how performance changes.